version: "3"

services:
  # Database
  database-service:
    image: mongo:latest
    restart: always
    container_name: ${LIDE_CONTAINER_DB}
    volumes:
      - database:/data/db
    environment:
      MONGO_INIT_DATABASE: ${LIDE_DB_NAME}
      MONGO_INIT_ROOT_USERNAME: ${LIDE_DB_USERNAME}
      MONGO_INIT_ROOT_PASSWORD: ${LIDE_DB_PASSWORD}
    ports:
      - ${LIDE_DB_PORT}:27017
    networks:
      - lidenetwork

  # Back-end Server
  lide-back-service:
    build: ./lide-back
    image: lide-back
    depends_on:
      - database-service
    links:
      - database-service
    restart: always
    container_name: ${LIDE_CONTAINER_BACK}
    hostname: ${LIDE_CONTAINER_BACK}
    volumes:
      - /app/node_modules
      - ./lide-back:/app
      - /lide-data:/lide-data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      DB_HOST: ${LIDE_CONTAINER_DB}
      DB_NAME: ${LIDE_DB_NAME}
      DB_PORT: ${LIDE_DB_PORT}
    env_file:
      - .env
    ports:
      - ${LIDE_BACK_PORT}:3000
    working_dir: /app
    entrypoint: node server.js
    #entrypoint: npm run dev
    networks:
      - lidenetwork

  # Web Server
  lide-web-service:
    build: ./lide-web
    image: lide-web
    restart: always
    container_name: ${LIDE_CONTAINER_WEB}
    hostname: ${LIDE_CONTAINER_WEB}
    volumes:
      - /app/node_modules
      - ./lide-web:/app
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LIDE_BACK_PORT: ${LIDE_BACK_PORT}
      BACK_HOST: ${LIDE_CONTAINER_BACK}
    env_file:
      - .env
    ports:
      - ${LIDE_WEB_PORT}:8080
    working_dir: /app
    entrypoint: npm run serve
    networks:
      - lidenetwork

  # WebSocket Server
  lide-wss-service:
    build: ./lide-wss
    image: lide-wss
    restart: always
    #container_name: ${LIDE_CONTAINER_WSS}
    #hostname: ${LIDE_CONTAINER_WSS}
    environment:
      LIDE_WSS_PORT: ${LIDE_WSS_PORT}
    env_file:
      - .env
    working_dir: /app
    ports:
      - ${LIDE_WSS_PORT}:8090
    entrypoint: node server_socket.js
    #network_mode: host

volumes:
  database:

networks:
  lidenetwork:
